### ISSUE TITLE
Refatoração da Wiki

### ISSUE THREAD

**Issue by lucasfcm9** [Interacao-Humano-Computador/2019.2-CPlusPlus#7]
### Descrição da Issue
Adição e refatoração de todos os documentos na *wiki* da disciplina de Interação Humano Computador. 

### Tasks: 
- [x] Adição de todos os documentos à *wiki*;
- [x] Validar com todos os integrantes do grupo;
- [x] Refatoração dos documentos da disciplina.

### Critérios de aceitação
- [x] Validação com todos os integrantes do grupo;
- [x] Ter todo o processo documentado;
- [x] Adicionar todos os documentos à Wiki.

**Comment by lucasfcm9** [comment]
![planning](https://user-images.githubusercontent.com/40740008/68158838-418fce00-ff2f-11e9-809a-58341af2a2ba.jpg)

**Comment by lucasfcm9** [comment]
![sb1](https://user-images.githubusercontent.com/40740008/68159613-e19a2700-ff30-11e9-8527-4cb105a48e40.jpg)

**Comment by lucasfcm9** [comment]
![sb2](https://user-images.githubusercontent.com/40740008/68159628-e9f26200-ff30-11e9-90c7-af9bfbc4589d.jpg)

**Comment by lucasfcm9** [comment]
<img width="488" alt="Screen Shot 2019-11-04 at 18 51 39" src="https://user-images.githubusercontent.com/40740008/68161599-f4aef600-ff34-11e9-8263-5816a7aef604.png">

**Comment by lucasfcm9** [comment]
<img width="488" alt="Screen Shot 2019-11-04 at 18 52 04" src="https://user-images.githubusercontent.com/40740008/68161613-fb3d6d80-ff34-11e9-86c1-3d9cd67636f6.png">

**Comment by lucasfcm9** [comment]
![swot_matrix](https://user-images.githubusercontent.com/40740008/68162448-cf22ec00-ff36-11e9-840e-db324edac03e.jpg)

**Comment by lucasfcm9** [comment]
<img width="506" alt="Diagrama busca info tabela" src="https://user-images.githubusercontent.com/40740008/68162891-eadac200-ff37-11e9-9e6e-34b046cc0a62.png">

**Comment by lucasfcm9** [comment]
![Diagrama busca info](https://user-images.githubusercontent.com/40740008/68162899-ee6e4900-ff37-11e9-846f-234c2dac9817.png)

**Comment by lucasfcm9** [comment]
<img width="432" alt="Responder forum tabela" src="https://user-images.githubusercontent.com/40740008/68162903-f201d000-ff37-11e9-8139-234077ce1abd.png">

**Comment by lucasfcm9** [comment]
![Responder forum](https://user-images.githubusercontent.com/40740008/68162906-f62ded80-ff37-11e9-844b-8dcac597267e.png)

**Comment by caiovfernandes** [comment]
![Screen Shot 2019-11-04 at 22 10 01](https://user-images.githubusercontent.com/42192251/68170785-e4584480-ff4f-11e9-82ce-30b4f618af42.png)

**Comment by lucasfcm9** [comment]
![IMAGE 2019-11-05 08:26:33](https://user-images.githubusercontent.com/40740008/68204073-f9f85900-ffa5-11e9-9ede-83fb90f46429.jpg)

**Comment by lucasfcm9** [comment]
<img width="560" alt="Screen Shot 2019-11-25 at 20 07 15" src="https://user-images.githubusercontent.com/40740008/69585778-6a036900-0fbf-11ea-8d01-c56ba759aab7.png">

**Comment by lucasfcm9** [comment]
<img width="483" alt="Screen Shot 2019-11-25 at 20 09 28" src="https://user-images.githubusercontent.com/40740008/69585806-843d4700-0fbf-11ea-97f5-6fda6198781d.png">

**Comment by lucasfcm9** [comment]
<img width="769" alt="Screen Shot 2019-11-25 at 20 17 38" src="https://user-images.githubusercontent.com/40740008/69586236-abe0df00-0fc0-11ea-8e0b-3abb3e3c2766.png">

**Comment by lucasfcm9** [comment]
<img width="1280" alt="Screen Shot 2019-11-28 at 07 07 07" src="https://user-images.githubusercontent.com/40740008/69797041-cf1cb180-11ad-11ea-8d46-47070cef2268.png">

**Comment by lucasfcm9** [comment]
![Identidade](https://user-images.githubusercontent.com/40740008/69800414-f7a7aa00-11b3-11ea-9267-12a5933603e7.png)
